databases:
  - name: chessonportfolio
    databaseName: chessonportfolio
    user: chessonportfolio

services:
  - type: web
    name: chessonportfolio
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chessonportfolio
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

